# Generated by Django 5.2.8 on 2025-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adcampaign',
            name='ad_spend',
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='daily_spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING_PICKUP', 'Waiting for Pickup'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned')], default='WAITING_PICKUP', max_length=30),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='campaign_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='platform',
            field=models.CharField(default='Meta', max_length=50),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform',
            field=models.CharField(default='Instagram', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
